name: Deploy-PRD
on:
  push:
    branches: [ "master" ]
    
# Inicio dos jobs
jobs:
  deploy:
    # Runner de execucao
    runs-on: ubuntu-latest

    # tarefas de execucao do CICD
    
    # 1 tarefa de checkout
    steps:
    - uses: actions/checkout@v3
    
    # 2 Setup do .NET Core utilizando a action padrao (setup) na V 6.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    # 3 - Dotnet restore direcionando para a estrutura (pasta)
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
      
    # 4 - Task de execucao
    - name: Dotnet Build
      run: |
        dotnet build --configuration Release
      working-directory: ./src
      
    # 5 - Add publish task
    - name: Dotnet publish
      run: |
        dotnet publish --configuration Release -o ./minhaapp
      working-directory: ./src
